const LOAD_CURRENCY = {
    REQUEST: 'REQUEST_CURRENCY',
    SUCCESS: 'REQUEST_CURRENCY_SUCCESS',
    FAIL: 'REQUEST_CURRENCY_FAIL',
}

const CURRENCY = {
    ADD: 'ADD_CURRENCY',
    DELETE: 'DELETE_CURRENCY'
}

const BASE_CURRENCY = {
    EDIT: 'EDIT_BASE_CURRENCY',
    UPDATE: 'UPDATE_BASAE_CURRENCY',
}


export default { LOAD_CURRENCY, CURRENCY, BASE_CURRENCY};